#!/usr/bin/env node
// Writes PRICING.md from the hub's public price list. Prices are never typed by hand:
//   node scripts/render-pricing.mjs            fetch https://api.mosadd.dev/v1/prices and write PRICING.md
//   node scripts/render-pricing.mjs --stdout   print instead of writing
// While the endpoint is not public, the file says so and carries only the policy (no numbers).
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

export const PRICES_URL = process.env.M0S_PRICES_URL || 'https://api.mosadd.dev/v1/prices';

const POLICY = `Prepaid, no plans. The test key (\`m0s_tk_test_…\`) is free. A top-up of at least 10 USD unlocks the full
line key (\`m0s_lk_live_…\`). Every call is held before it runs and settled after it; with an empty balance the
hub answers 402. Usage per call: [app.mosadd.dev](https://app.mosadd.dev) → Usage.`;

const usd = (micros, per) => {
  const v = Number(micros) / 1e6;
  const s = v >= 0.01 ? v.toFixed(2) : v.toFixed(6).replace(/0+$/, '');
  return `${s} USD${per && Number(per) !== 1 ? ` per ${Number(per).toLocaleString('en-US')}` : ''}`;
};

/** Render PRICING.md from the endpoint answer (or from the failure to get one). */
export function renderPricing(result, measuredAt = new Date().toISOString().slice(0, 10)) {
  const head = `# Pricing\n\n<!-- GENERATED by scripts/render-pricing.mjs from ${PRICES_URL} — do not edit by hand. -->\n\n${POLICY}\n\n`;
  if (!result.ok) {
    return `${head}## Unit prices\n\nNot published yet: \`GET ${PRICES_URL}\` answered HTTP ${result.status} on ${measuredAt}.\nThis file lists prices only once the hub publishes them; they are never typed in by hand.\n`;
  }
  const rows = (result.body.prices ?? result.body.data ?? result.body).map(
    (p) => `| \`${p.meter_id ?? p.meter}\` | ${p.unit ?? ''} | ${usd(p.unit_price_micros, p.per_units)} |`,
  );
  return `${head}## Unit prices (from the hub, ${measuredAt})\n\n| Meter | Unit | Price |\n|---|---|---|\n${rows.join('\n')}\n`;
}

export async function fetchPrices(fetchImpl = globalThis.fetch) {
  try {
    const r = await fetchImpl(PRICES_URL, { headers: { accept: 'application/json' } });
    return r.ok ? { ok: true, status: r.status, body: await r.json() } : { ok: false, status: r.status };
  } catch (e) {
    return { ok: false, status: `unreachable (${e.message})` };
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const md = renderPricing(await fetchPrices());
  if (process.argv.includes('--stdout')) process.stdout.write(md);
  else writeFileSync(join(dirname(fileURLToPath(import.meta.url)), '..', 'PRICING.md'), md);
}
