#!/usr/bin/env node
// Writes PRICING.md from the hub's public price list. Prices are never typed by hand:
//   node scripts/render-pricing.mjs            fetch https://api.mosadd.dev/v1/pricing and write PRICING.md
//   node scripts/render-pricing.mjs --stdout   print instead of writing
//   node scripts/render-pricing.mjs --check    exit 1 when PRICING.md no longer matches the live list
//
// The endpoint is GET /v1/pricing (public, no key). It answers
//   { items: [{ meter_id, label, unit, state: 'live'|'soon', display_price_micros, unit_price_micros, per_units,
//               display_per, note, verified_at, ... }], billing, plans, currency, rounding, min_topup_usd, scheduled, measured_at }
// (measured 2026-09-29; SPEC-DYSTRYBUCJA says /v1/prices, the hub serves /v1/pricing — /v1/prices answers 404).
// While the endpoint cannot be read, the file says so and carries only the policy, never a number from memory.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

export const PRICES_URL = process.env.M0S_PRICES_URL || 'https://api.mosadd.dev/v1/pricing';
const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'PRICING.md');

/** Exact decimal USD from micro-dollars (no rounding: 12000 -> "0.012", 100 -> "0.0001"). */
export function usd(micros) {
  const n = Number(micros);
  if (!Number.isFinite(n) || n < 0 || !Number.isInteger(n)) throw new Error(`price is not a whole number of micro-dollars: ${micros}`);
  const whole = Math.floor(n / 1e6);
  const frac = String(n % 1e6).padStart(6, '0').replace(/0+$/, '');
  return `${whole}${frac ? '.' + frac : ''} USD`;
}

const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();

function policy(body) {
  const min = body?.min_topup_usd;
  return [
    `Prepaid${body?.plans === false ? ', no plans' : ''}. The test key (\`m0s_tk_test_…\`) is free.` +
      (min ? ` A top-up of at least ${min} ${body.currency || 'USD'} unlocks the full line key (\`m0s_lk_live_…\`).` : ''),
    'Every call is held before it runs and settled after it; with an empty balance the hub answers 402.',
    body?.rounding ? cell(body.rounding) : null,
    'Usage per call: [app.mosadd.dev](https://app.mosadd.dev) → Usage.',
  ]
    .filter(Boolean)
    .join('\n');
}

/** Render PRICING.md from the endpoint answer (or from the failure to get one). */
export function renderPricing(result, measuredAt = new Date().toISOString().slice(0, 10)) {
  const head = `# Pricing\n\n<!-- GENERATED by scripts/render-pricing.mjs from ${PRICES_URL} — do not edit by hand. -->\n\n`;
  if (!result.ok) {
    return (
      `${head}Prepaid, no plans. The test key (\`m0s_tk_test_…\`) is free. Every call is held before it runs and settled after it;\n` +
      `with an empty balance the hub answers 402.\n\n## Unit prices\n\nNot available: \`GET ${PRICES_URL}\` answered HTTP ${result.status} on ${measuredAt}.\n` +
      `This file lists prices only from the hub's own list; they are never typed in by hand.\n`
    );
  }
  const body = result.body;
  if (!body || !Array.isArray(body.items)) throw new Error(`${PRICES_URL} answered without an "items" array; not rendering a price list`);
  const items = [...body.items].sort((a, b) => (a.sort ?? 0) - (b.sort ?? 0));
  const row = (p) => `| ${cell(p.label)} | ${usd(p.display_price_micros)} per ${cell(p.unit)} | ${cell(p.note)} | \`${cell(p.meter_id)}\` |`;
  const table = (list) => `| Service | Price | Note | Meter |\n|---|---|---|---|\n${list.map(row).join('\n')}\n`;
  const live = items.filter((p) => p.state === 'live');
  const soon = items.filter((p) => p.state !== 'live');
  const verified = [...new Set(items.map((p) => String(p.verified_at || '').slice(0, 10)).filter(Boolean))].join(', ');
  const asOf = String(body.measured_at || measuredAt).slice(0, 10);
  let md = `${head}${policy(body)}\n\n## Billed today\n\n${table(live)}`;
  if (soon.length) md += `\n## Priced, not billed yet\n\nThese meters have a price in the hub's list but are not live; nothing is charged for them today.\n\n${table(soon)}`;
  if (Array.isArray(body.scheduled) && body.scheduled.length) {
    md += `\n## Scheduled changes\n\n${body.scheduled.map((s) => `- \`${cell(s.meter_id)}\`: ${usd(s.display_price_micros ?? s.unit_price_micros)} from ${cell(s.effective_from)}`).join('\n')}\n`;
  }
  md += `\nSource: \`GET ${PRICES_URL}\` (${asOf}${verified ? `; prices verified ${verified}` : ''}). The hub's list wins over this file.\n`;
  return md;
}

export async function fetchPrices(fetchImpl = globalThis.fetch) {
  try {
    const r = await fetchImpl(PRICES_URL, { headers: { accept: 'application/json' } });
    return r.ok ? { ok: true, status: r.status, body: await r.json() } : { ok: false, status: r.status };
  } catch (e) {
    return { ok: false, status: `unreachable (${e.message})` };
  }
}

/** PRICING.md without the date lines, so --check compares prices and not the day it ran. */
const undated = (md) => md.replace(/\r\n/g, '\n').replace(/^Source: .*$/m, '');

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const result = await fetchPrices();
  const md = renderPricing(result);
  if (process.argv.includes('--check')) {
    if (!result.ok) {
      console.error(`cannot read ${PRICES_URL}: HTTP ${result.status}`);
      process.exit(1);
    }
    if (undated(readFileSync(OUT, 'utf8')) !== undated(md)) {
      console.error(`PRICING.md differs from ${PRICES_URL} - run: node scripts/render-pricing.mjs`);
      process.exit(1);
    }
    console.log(`PRICING.md matches ${PRICES_URL} (${result.body.items.length} meters)`);
  } else if (process.argv.includes('--stdout')) process.stdout.write(md);
  else writeFileSync(OUT, md);
}
